# -*- coding: utf-8 -*-
"""Loops.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MEgbQK_J_gPPK5sccaD57YRbefeiWQw9
"""

#PRINT NUMBERS 1 TO 5

for i in range (1 , 6 ) :
  print(i)

#PRINT NUMBERS BETWEEN 1 TO 10

for i in range (1, 11 , 2 ):
 print(i)


#PRINT NESTED LOOP

for i in range ( 3 ) :
  for j in range ( 2 ) :
    print( i, j )

#PRINT  NUMBERS BETWEEN 1 TO 7 AND STOP WHEN 5

for i in range ( 1 , 8 ):
if i == 5:
  break
print(i)